### ISSUE TITLE
Maximum callstack exceeded

### ISSUE THREAD

**Issue by ihack2712** [c4spar/deno-cliffy#323]
```
error: Uncaught RangeError: Maximum call stack size exceeded
    const row = new this(...cells);
                ^
    at Function.from (https://deno.land/x/cliffy@v0.20.1/table/row.ts:27:17)
    at TableLayout.createRow (https://deno.land/x/cliffy@v0.20.1/table/layout.ts:156:16)
    at TableLayout.spanRows (https://deno.land/x/cliffy@v0.20.1/table/layout.ts:131:29)
    ...
    at TableLayout.spanRows (https://deno.land/x/cliffy@v0.20.1/table/layout.ts:148:17)
    at TableLayout.createLayout (https://deno.land/x/cliffy@v0.20.1/table/layout.ts:54:36)
    at TableLayout.toString (https://deno.land/x/cliffy@v0.20.1/table/layout.ts:32:40)
    at Table.toString (https://deno.land/x/cliffy@v0.20.1/table/table.ts:126:48)
    at Table.render (https://deno.land/x/cliffy@v0.20.1/table/table.ts:131:22)
    at file:///Users/jb/Downloads/table.ts:80:6
```

code

```ts
// Imports
import { parse } from "https://deno.land/std@0.129.0/encoding/csv.ts";
import { resolve } from "https://deno.land/std@0.129.0/path/mod.ts";
import {
  Cell,
  Row,
  Table,
} from "https://deno.land/x/cliffy@v0.20.1/table/mod.ts";
import { green, red } from "https://deno.land/std@0.129.0/fmt/colors.ts";

interface Item {
  at: Date;
  type: string;
  description: string;
  total: number;
  fee: number;
  receiver?: string;
  account: string;
}

const items: Item[] = [];

for (const filename of Deno.args.map((filename) => resolve(filename))) {
  const data = JSON.parse(Deno.readTextFileSync(filename)) as Item[];
  items.push(...(data.map((value) => (value.at = new Date(value.at), value))));
}

console.log(items.filter((item) => item.total === undefined));

const data = items.sort((a, b) => a.at.getTime() - b.at.getTime()).map(
  (
    { account, at, description, fee, total, type, receiver },
    _1?: unknown,
    _2?: unknown,
    netto = total - fee,
  ) => {
    return [
      Cell.from(account).align("center"),
      Cell.from(
        at.getDate().toString().padStart(2, "0") + "/" +
          (at.getMonth() + 1).toString().padStart(2, "0") + "/" +
          at.getFullYear(),
      ),
      Cell.from(type).align("center"),
      Cell.from(
        (total > 0 ? green : total < 0 ? red : (s: string) => s)(
          (total < 0 ? total * -1 : total).toFixed(2),
        ),
      ).align("right"),
      Cell.from(
        (fee > 0 ? green : fee < 0 ? red : (s: string) => s)(
          (fee < 0 ? fee * -1 : fee).toFixed(2),
        ),
      ).align("right"),
      Cell.from(
        (netto > 0 ? green : netto < 0 ? red : (s: string) => s)(
          (netto < 0 ? netto * -1 : netto).toFixed(2),
        ),
      ).align("right"),
      Cell.from(description).align("left"),
      Cell.from(receiver || "").align("left"),
    ];
  },
);
(Error as any).stackTraceLimit = 99999;
try {
  new Table()
    .header(Row.from([
      Cell.from("Account").align("center"),
      Cell.from("Dato").align("center"),
      Cell.from("Type").align("center"),
      Cell.from("Totalt Beløp").align("center"),
      Cell.from("Avgift").align("center"),
      Cell.from("Netto").align("center"),
      Cell.from("Beskrivelse").align("left"),
      Cell.from("Konto").align("center"),
    ]))
    .body(data)
    .border(true)
    .render();
} catch (error) {
  throw error;
}
```

**Comment by c4spar** [comment]
I have added a performance improvement in #327 which solves the issue for tables without col and row span. For col and row span it's simply to much data. Maybe i can solve the issue with an async method or by chunking the data with an async itarator.
Does the fix solve the issue for you? it's currently available in the main branch.

**Comment by ihack2712** [comment]
Yup it works now
