### ISSUE TITLE
Not working with dtn

### ISSUE THREAD

**Issue by UltiRequiem** [c4spar/deno-cliffy#339]
You can get this output at the moment of running 
https://github.com/UltiRequiem/is-number/blob/main/scripts/node_support.ts

```
node/src/deps/deno.land/x/cliffy@v0.22.2/command/command.ts:1243:34 - error TS2366: Function lacks ending return statement and return type does not include 'undefined'.

1243   protected error(error: Error): Error {
                                      ~~~~~

error: Uncaught (in promise) Error: Had 1 diagnostics.
      throw new Error(`Had ${diagnostics.length} diagnostics.`);
            ^
    at build (https://deno.land/x/dnt@0.22.0/mod.ts:276:13)
    at async buildPackage (https://deno.land/x/ultirequiem@0.0.11/node_support.ts:41:3)
```

**Comment by UltiRequiem** [comment]
I get it working deactivating type-checking, but not ideal
https://github.com/denoland/dnt#disabling-type-checking-testing-declaration-emit-or-commonjsumd-output
