### ISSUE TITLE
Test command in CONTRIBUTING.md does not run successfully

### ISSUE THREAD

**Issue by robinmorton** [c4spar/deno-cliffy#373]
Executing the command in the `CONTRIBUTING.md` file results in failures due to deno not having permissions to `read` or `run` e.g.

```
> deno test -r --allow-env --unstable   

PermissionDenied: Requires run access to "deno", run again with the --allow-run flag
  const process = Deno.run({
                       ^
    at Object.opSync (deno:core/01_core.js:172:12)
    at opRun (deno:runtime/js/40_process.js:28:17)
    at Object.run (deno:runtime/js/40_process.js:111:17)
    at runPrompt (file:///Users/robinmorton/Github/deno-cliffy/prompt/test/integration/test.ts:62:24)
    at async fn (file:///Users/robinmorton/Github/deno-cliffy/prompt/test/integration/test.ts:20:32)

failures:

        ./command/test/integration/test.ts
        command integration
        ./prompt/test/integration/test.ts
        prompt - integration - checkbox
        prompt - integration - confirm
        prompt - integration - input
        prompt - integration - input no location flag
        prompt - integration - input no prefix
        prompt - integration - input prefix
        prompt - integration - input suggestions
        prompt - integration - list
        prompt - integration - number
        prompt - integration - number decimal
        prompt - integration - secret
        prompt - integration - select
        prompt - integration - toggle

test result: FAILED. 644 passed (8 steps); 14 failed (14 steps); 0 ignored; 0 measured; 0 filtered out (7s)

error: Test failed
```

and

```
> deno test -r --allow-env --allow-run --unstable   

failures:

./command/test/integration/test.ts > command integration
Error: 14 test steps failed.
    at runTest (deno:runtime/js/40_testing.js:803:11)
    at async Object.runTests (deno:runtime/js/40_testing.js:1105:22)

failures:

        ./command/test/integration/test.ts
        command integration

test result: FAILED. 644 passed (8 steps); 1 failed (14 steps); 0 ignored; 0 measured; 0 filtered out (10s)

error: Uncaught PermissionDenied: Requires read access to <CWD>, run again with the --allow-read flag
    root = Deno.cwd(),
                ^
    at Object.opSync (deno:core/01_core.js:172:12)
    at Object.cwd (deno:runtime/js/30_fs.js:65:17)
    at expandGlob (https://deno.land/std@0.137.0/fs/expand_glob.ts:78:17)
    at file:///Users/robinmorton/Github/deno-cliffy/prompt/test/integration/test.ts:13:37
```

**Comment by robinmorton** [comment]
I'm working on a fix for this and will open a PR soon.
