### ISSUE TITLE
UpgradeCommand does not work when run on binaries created by deno compile.

### ISSUE THREAD

**Issue by ryo-ma** [c4spar/deno-cliffy#538]
UpgradeCommand does not work when run on binaries created by deno compile.

For example project: https://github.com/c-3lab/dim

1. Clone project
```
git clone https://github.com/c-3lab/dim
cd dim
```

2. Edit version in lib/consts.ts.
```
- export const VERSION = "v1.0.2";
+ export const VERSION = "v1.0.0";
```
3. Compile
```
./cross_compile.sh
```

4. Rename the binary to dim and Move the binary file to /usr/local/bin
The compiled file name is different for each OS.

5. chmod
```
chmod u+x /usr/loca/bin/dim
```

7. Run the upgrade command
```
$ dim upgrade
```

Raise the following error.
```
  error: Unknown option "--allow-run". Did you mean option "--force"?

error: Uncaught (in promise) Error: Failed to upgrade dim from v1.0.1 to version v1.0.2!
            throw new Error(`Failed to upgrade ${name} from ${from} to version ${to}!`);
                  ^
    at GithubProvider.upgrade (https://deno.land/x/cliffy@v0.25.7/command/upgrade/provider.ts:60:19)
    at async UpgradeCommand.fn (https://deno.land/x/cliffy@v0.25.7/command/upgrade/upgrade_command.ts:29:17)
    at async UpgradeCommand.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:696:13)
    at async UpgradeCommand.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:584:20)
    at async file:///Users/xxxx/dim/dim.ts:4:1
```

**Comment by c4spar** [comment]
duplicate of #302
