### ISSUE TITLE
Warnings about Deno.stdin in v1.40.1

### ISSUE THREAD

**Issue by PrpAcline** [c4spar/deno-cliffy#671]
With the recent update there seems to be some methods used that will be depreciated and produce a very annoying warning.

```warning: Use of deprecated "Deno.isatty()" API. This API will be removed in Deno 2.

Stack trace:
  at Secret.#readChar (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_prompt.ts:359:24)
  at Secret.#readKey (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_prompt.ts:351:50)
  at Secret.read (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_prompt.ts:245:57)
  at Secret.read (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/secret.ts:96:18)
  at Secret.#execute (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_prompt.ts:182:21)
  at async Secret.prompt (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_prompt.ts:161:14)
  at async Command.actionHandler (file:///Users/acline/code/admin-cli/main.ts:14:32)
  at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
  at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)

hint: Use `Deno.stdin.isTerminal()`, `Deno.stdout.isTerminal()` or `Deno.stderr.isTerminal()` instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.```

**Comment by willem-haring** [comment]
Experiencing exactly the same

**Comment by andrewthauer** [comment]
Had a look at updating this to non deprecated code. After a short attempt, this seems like it may be non trivial to update and may require breaking changes to the API. Although, I'm not overly familiar with the code.

**Comment by iuioiua** [comment]
I've submitted a fix for this issue in #672. Until the PR is merged and a release is published, you can also set the `DENO_NO_DEPRECATION_WARNINGS=1` environment variable to suppress these deprecation warnings. It's a bit better than `--quiet` in that it doesn't suppress other, possibly useful warnings.

**Comment by andrewthauer** [comment]
@iuioiua - Nice. I was actually looking at the broader deprecation warnings which span a lot of code and API surface unfortunately. This is a nice first step though! I recently found https://docs.deno.com/runtime/manual/advanced/migrate_deprecations which has a few things I wasn't aware of. Once yours lands I might take a stab at the rest.

**Comment by iuioiua** [comment]
@andrewthauer, where?

**Comment by andrewthauer** [comment]
@iuioiua - It looks like only `Deno.isatty` is flagged, but if you dig in (mostly in `ansi` & `prrompt` modules) there is usage of `Deno.ReaderSync`, & `Deno.WriterSync` etc. TBH - I may have been confused by the deprecation warning saying use `ReadableStream` & `WritableStream` until I realized that there are types in `std/io` for `ReaderSync` / `WriterSync`. Changing these to streams would require a huge change to the API to be async vs sync I think. But perhaps this is not the case after all. Maybe you can confirm?

**Comment by iuioiua** [comment]
Oh, right. Yeah, those can be swapped easily with the types from https://deno.land/std/io/types.ts.
