### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'icon')

### ISSUE THREAD

**Issue by Debargha2001** [c4spar/deno-cliffy#685]
```
const promptResult = await Checkbox.prompt<string>({
        message: "Select images(Selected images will be prefetched):",
        hint: "Use Up/Down arrow keys to navigate. Space to select, Enter to confirm",
        maxRows: 20,
        options: groupServiceOptions,
```
In the above code I am getting the following error while executing:
TypeError: Cannot read properties of undefined (reading 'icon')
    at Checkbox.getCheckboxIcon (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/checkbox.ts:173:17)
    at Checkbox.getListItemIcon (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/checkbox.ts:170:17)
    at Checkbox.getListItem (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_list.ts:218:18)
    at Checkbox.getList (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_list.ts:204:22)
    at Checkbox.body (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_list.ts:157:17)
    at Checkbox.render (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_prompt.ts:82:18)
    at Checkbox.#execute (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_prompt.ts:62:16)
    at Checkbox.prompt (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/_generic_prompt.ts:49:33)
    at Function.prompt (https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/checkbox.ts:81:30)
    at Module.install (file:///home/devdd/Workspace/Wobot/woconnect_utils/lib/action.ts:635:39)
But This error is gone when I increase value of maxRows to 25

**Comment by c4spar** [comment]
Can you please show me what groupServiceOptions looks like?

**Comment by Debargha2001** [comment]
> Can you please show me what groupServiceOptions looks like?

`const groupServiceOptions = [
  {
    name: "CORE,
    value: "Core",
    checked: true,
    disabled: true
  },
  { name: " - Debugger Service" },
  { name: " - Local Database" },
  { name: " - Remote Manager" },
  { name: " - Updater Service" },
  { name: " - Test Service 1" },
  {
    name: "Service Group 1",
    value: "Service Group 1",
    checked: false,
    disabled: true
  },
  {
    name: " - Service 1"
  },
  {
    name: " - Service 2"
  },
  { name: " - Service 3" },
  {
    name: " - Service 4"
  },
  {
    name: "Service Group 2",
    value: "Service Group 2",
    checked: false,
    disabled: true
  },
  {
    name: " - Service 1"
  },
  {
    name: " - Service 2"
  },
  {
    name: " - Service 3"
  },
  { name: " - Service 4" },
  {
    name: " - Service 5"
  },
  {
    name: "Service Group 3",
    value: "Service Group 3",
    checked: false,
    disabled: true
  },
  { name: " - Service 1" },
  {
    name: " - Service 2"
  },
  { name: "Miscellaneous Services" },
  {
    name: " Test Service",
    value: "Test Service",
    checked: false,
    disabled: false
  },
  {
    name: "Advance Options",
    value: "advance"
  }
]`

This is the structure of groupServiceOptions
