### ISSUE TITLE
variadic args prevent any subsequent options

### ISSUE THREAD

**Issue by andykais** [c4spar/deno-cliffy#716]
a sample script like this:
```ts
import * as cliffy from 'jsr:@cliffy/command@1.0.0-rc.4'

const cli = new cliffy.Command()
  .name('test')
  .option('--files <...files:string>', 'A list of files to watch')
  .option('--foobar', 'A foobar')
  .action(opts => {
    console.log({opts})
  })

cli.parse()
```
when called like so: `deno run --check test.ts --files foo,bar --foobar` produces the following output
```
{ opts: { files: [ "foo,bar", "--foobar" ] } }
```

This means that users of a cli tool need to know which args are variadic and remember to put them last. I also imagine this means theres no way to specify more than one option that accepts variadic arguments. One possible way to handle these cases would be if I could specify a delimeter for variadic args. E.g. a comma (you can see in the example above that comma separated values are currently read as a single value. To avoid making it break existing clis, this could be an optional arg on the `option` method.

Also, while testing this I realized that the same command with an `=` character hits an infinite recursion loop:
`deno run --check test.ts --files=foo,bar`
```
error: Uncaught (in promise) RangeError: Maximum call stack size exceeded
      function parseValue(
               ^
    at parseValue (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:411:16)
    at parseNext (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:347:20)
    at parseNext (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:373:11)
    at parseNext (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:373:11)
    at parseNext (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:373:11)
    at parseNext (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:373:11)
    at parseNext (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:373:11)
    at parseNext (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:373:11)
    at parseNext (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:373:11)
    at parseNext (https://jsr.io/@cliffy/flags/1.0.0-rc.4/flags.ts:373:11)
```

**Comment by andykais** [comment]
another option would be allowing commands to be specified more than once. E.g.
```bash
deno run --check test.ts --watch foo --watch bar
```

**Comment by Arnaud73** [comment]
Have you tried ` .option('--files <files:string[]>', 'A list of files to watch')` instead?
